-- AlterTable
ALTER TABLE "school_settings"
ADD COLUMN "enabled_alert_types" TEXT[] NOT NULL DEFAULT ARRAY['STUDENT_LATE', 'STUDENT_ABSENT', 'EXCESSIVE_STUDENT_EXITS', 'HIGH_NOISE_EVENT', 'DEVICE_OFFLINE']::TEXT[],
ADD COLUMN "enabled_insight_types" TEXT[] NOT NULL DEFAULT ARRAY['RECURRING_STUDENT_LATENESS', 'EXCESSIVE_STUDENT_MOVEMENT', 'CHRONIC_CLASSROOM_NOISE', 'DEVICE_RELIABILITY_ISSUE']::TEXT[];
